# Generated by Django 4.2.8 on 2023-12-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_remove_employee_leave_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cost_center',
            field=models.CharField(default=1, max_length=30, verbose_name='Centro de custo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='production_line',
            field=models.CharField(max_length=14, verbose_name='Linha'),
        ),
    ]
