# Generated by Django 4.2.8 on 2023-12-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0005_employee_cost_center_alter_employee_production_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='employee',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='control_panel.employee'),
            preserve_default=False,
        ),
    ]
