# Generated by Django 4.2.8 on 2023-12-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0007_remove_users_employee_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='class_field',
            field=models.CharField(db_column='class', default=1, max_length=30, verbose_name='Turma'),
            preserve_default=False,
        ),
    ]
