# Generated by Django 4.2.8 on 2023-12-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0008_employee_class_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='class_field',
            field=models.CharField(choices=[('A', 'Turma A'), ('B', 'Turma B'), ('C', 'Turma C'), ('D', 'Turma D'), ('E', 'Turma E')], db_column='class', max_length=30, verbose_name='Turma'),
        ),
    ]
