# Generated by Django 4.2.8 on 2023-12-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0011_course_employee_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Número',
                'verbose_name_plural': 'Números',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='production_line',
        ),
        migrations.AddField(
            model_name='employee',
            name='production_line',
            field=models.ManyToManyField(related_name='production_lines', to='control_panel.productionline'),
        ),
    ]
