# Generated by Django 4.2.8 on 2023-12-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0012_productionline_remove_employee_production_line_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionline',
            options={'verbose_name': 'Linha', 'verbose_name_plural': 'Linhas'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='production_line',
            field=models.ManyToManyField(related_name='employees', to='control_panel.productionline', verbose_name='Linha'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
