# Generated by Django 4.2.8 on 2023-12-27 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0013_alter_productionline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionline',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Linha'),
        ),
    ]
