# Generated by Django 4.2.8 on 2023-12-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0014_productionline_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionline',
            name='number',
        ),
        migrations.AlterField(
            model_name='productionline',
            name='id',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False, verbose_name='Linha'),
        ),
    ]
