# Generated by Django 4.2.8 on 2023-12-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0016_alter_job_job_title_alter_productionline_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='class_field',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], db_column='class', max_length=30, null=True, verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='Employees', to='control_panel.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='profile/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='production_line',
            field=models.ManyToManyField(null=True, related_name='employees', to='control_panel.productionline', verbose_name='Linha'),
        ),
    ]
