# Generated by Django 4.2.8 on 2023-12-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0017_alter_employee_class_field_alter_employee_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='Employees', to='control_panel.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='production_line',
            field=models.ManyToManyField(blank=True, related_name='employees', to='control_panel.productionline', verbose_name='Linha'),
        ),
    ]
