# Generated by Django 4.2.8 on 2023-12-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0018_alter_employee_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='class_field',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], db_column='class', max_length=30, null=True, verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='production_line',
            field=models.ManyToManyField(related_name='employees', to='control_panel.productionline', verbose_name='Linha'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Gerente', 'Gerente'), ('Supervisor', 'Supervisor'), ('Padrão', 'Padrão')], max_length=100, verbose_name='Permissão'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
