# Generated by Django 4.2.8 on 2023-12-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0019_alter_employee_class_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Gerente', 'Gerente'), ('Supervisor', 'Supervisor'), ('Padrão', 'Padrão')], default=1, max_length=100, verbose_name='Permissão'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='production_line',
            field=models.ManyToManyField(blank=True, related_name='employees', to='control_panel.productionline', verbose_name='Linha'),
        ),
    ]
