# Generated by Django 4.2.8 on 2024-01-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0020_remove_employee_role_users_role_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.AddField(
            model_name='employee',
            name='neighborhood',
            field=models.CharField(default=2, max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='street',
            field=models.CharField(default=2, max_length=100, verbose_name='Rua'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sobrenome'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
