# Generated by Django 4.2.8 on 2024-01-08 01:33

import control_panel.validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0021_remove_employee_address_employee_neighborhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, validators=[control_panel.validator.validate_phone_number], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto'),
        ),
    ]
