# Generated by Django 4.2.8 on 2024-01-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0025_alter_job_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(choices=[('Supervisor', 'Supervisor'), ('Gerente', 'Gerente'), ('Administrador', 'Administrador'), ('Operador Produção 1', 'Operador de Produção 1'), ('Operador Produção 2', 'Operador de Produção 2'), ('Técnico Eletrônico', 'Técnico Eletrônico'), ('Mecânico de Manutenção', 'Mecânico de Manutenção'), ('Inspetor de Qualidade', 'Inspetor de Qualidade'), ('Montador de Equipamentos', 'Montador de Equipamentos'), ('Operador Máquinas CNC', 'Operador de Máquinas CNC'), ('Soldador', 'Soldador'), ('Eletricista Industrial', 'Eletricista Industrial'), ('Técnico Automação Industrial', 'Técnico em Automação Industrial')], max_length=100, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='available_hours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control_panel.availablehours'),
            preserve_default=False,
        ),
    ]
