# Generated by Django 4.2.8 on 2024-01-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0026_availablehours_alter_job_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablehours',
            name='end_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availablehours',
            name='initial_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
