# Generated by Django 4.2.8 on 2024-01-10 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0027_alter_availablehours_end_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='available_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_panel.availablehours'),
        ),
    ]
