# Generated by Django 4.2.8 on 2024-01-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0031_remove_employee_available_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponível')),
                ('day', models.CharField(max_length=15, verbose_name='Dia')),
                ('initial', models.TimeField(blank=True, default=None, null=True)),
                ('end', models.TimeField(blank=True, default=None, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_hours', to='control_panel.employee', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name_plural': 'Horários disponivéis',
            },
        ),
        migrations.DeleteModel(
            name='AvailableHours',
        ),
    ]
