# Generated by Django 4.2.8 on 2024-01-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0035_alter_employee_class_field_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='production_line',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='control_panel.productionline', verbose_name='Linha'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Ajudante geral', 'Ajudante geral'), ('Aprendiz', 'Aprendiz'), ('Eletrônico', 'Eletrônico'), ('Engenheiro Eletrônico', 'Engenheiro Eletrônico'), ('Estagiário', 'Estagiário'), ('Gerente', 'Gerente'), ('Mecânico', 'Mecânico'), ('Op produção I', 'Op produção I'), ('Op produção II', 'Op produção II'), ('Op produção III', 'Op produção III'), ('Op produção IV', 'Op produção IV'), ('Op produção V', 'Op produção V'), ('Op produção VI', 'Op produção VI'), ('Planejador', 'Planejador'), ('Técnico mecânico', 'Técnico mecânico'), ('Técnico de processo', 'Técnicos de processo'), ('Supervisor', 'Supervisor'), ('Sup produção', 'Sup produção')], max_length=30, verbose_name='Cargo'),
        ),
    ]
