# Generated by Django 4.2.8 on 2024-01-17 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0036_alter_employee_production_line_alter_job_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_filled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Disponibilidade',
            },
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Dia')),
                ('initial_time', models.TimeField(blank=True, default=None, null=True)),
                ('end_time', models.TimeField(blank=True, default=None, null=True)),
                ('availabilty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='control_panel.availability')),
            ],
            options={
                'verbose_name_plural': 'Dia da semana',
            },
        ),
        migrations.DeleteModel(
            name='AvailableTimes',
        ),
        migrations.AddField(
            model_name='employee',
            name='availability',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='control_panel.availability'),
        ),
    ]
