# Generated by Django 4.2.8 on 2024-01-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0037_availability_dayofweek_delete_availabletimes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayofweek',
            old_name='availabilty',
            new_name='availability',
        ),
    ]
