# Generated by Django 4.2.8 on 2024-01-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0039_productionline_name_productionline_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionline',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nome'),
        ),
    ]
