# Generated by Django 4.2.8 on 2024-01-22 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0040_alter_productionline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_vacations',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Última férias'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name='Data de contratação'),
        ),
    ]
