# Generated by Django 4.2.8 on 2024-01-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0041_employee_last_vacations_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, verbose_name='Data de contratação'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_vacations',
            field=models.DateField(blank=True, null=True, verbose_name='Última férias'),
        ),
    ]
