# Generated by Django 4.2.8 on 2024-01-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0043_alter_employee_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='availability',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='control_panel.availability'),
        ),
    ]
