# Generated by Django 4.2.8 on 2024-02-01 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0045_alter_employee_last_vacations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='availability',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.availability'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
